apiVersion: v1
kind: Service
metadata:
  name: {{ include "molt-lms.fullname" . }}-orchestrator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molt-lms.labels" . | nindent 4 }}
    release: {{ .Values.orchestrator.releaseName }}
  {{- with .Values.orchestrator.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.orchestrator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      name: orch
    - port: {{ .Values.orchestrator.service.metricsPort }}
      name: orch-metrics
  selector:
    {{- include "molt-lms.selectorLabels" . | nindent 4 }}
    release: {{ .Values.orchestrator.releaseName }}
  {{- with .Values.orchestrator.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
